<?php

/**
 * Load the necessary include files.
 */
module_load_include('inc', 'google_analytics_counter', 'google_analytics_counter_settings');
module_load_include('inc', 'google_analytics_counter', 'google_analytics_counter_data');
module_load_include('inc', 'google_analytics_counter', 'google_analytics_counter_auth');

/**
 * Valid permissions for this module
 * @return array An array of valid permissions for the test_module module
 */
function google_analytics_counter_permission() {
  return array(
    /* Perhaps for later:
    'access google analytics counter' => array(
      'title' => t('Access Google Analytics Counter'),
      'description' => t('Set roles that may access the output of Google Analytics Counter.'),
      ),
    */
    'administer google analytics counter' => array(
      'title' => t('Administer Google Analytics Counter'),
      'description' => t('Set roles that may access the settings of Google Analytics Counter.'),
      ),
    );
}

/**
 * Display help and module information
 * Implements hook_help().
 * @param path which path of the site we're displaying help
 * @param arg array that holds the current path as would be returned from arg() function
 * @return help text for the path
 */
function google_analytics_counter_help($path, $arg) {
  if ($path == 'admin/help#google_analytics_counter') {
    //admin/modules#description
    //admin/help/google_analytics_counter
    // '<p>' . t("Page view counter drawing on data collected by Google Analytics.") . '</p>';
    $output = file_get_contents(drupal_get_path('module', 'google_analytics_counter') . '/README.txt');
    return nl2br($output);
  }
}

/**
 * Menu for this module
 * @return array An array with this module's settings.
 */
function google_analytics_counter_menu() {
  $items = array();

  $items['admin/config/system/google_analytics_counter'] = array(
    'title' => 'Google Analytics Counter',
    'description' => 'Configure Google Analytics Counter module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('google_analytics_counter_admin'),
    'access arguments' => array('administer google analytics counter'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 10,
    );

  $items['admin/config/system/google_analytics_counter/settings'] = array(
    'title' => 'Settings',
    'description' => 'General settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('google_analytics_counter_admin'),
    'access arguments' => array('administer google analytics counter'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
    );

  $items['admin/config/system/google_analytics_counter/details'] = array(
    'title' => 'Details',
    'description' => 'More information relevant to Google Analytics statistics for this site.',
    'page callback' => 'google_analytics_counter_details',
    'access arguments' => array('administer google analytics counter'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
    );

  $items['admin/config/system/google_analytics_counter/authentication'] = array(
    'title' => 'GA authentication',
    'description' => 'Authenticate access to a Google Analytics profile.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('google_analytics_counter_auth_admin'),
    'access arguments' => array('administer google analytics counter'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 4,
    );

  // A shortcut to the permissions settings for this module.
  $items['admin/config/system/google_analytics_counter/permissions'] = array(
    'title' => 'Permissions',
    'description' => 'Configure access permissions',
    'page callback' => 'google_analytics_counter_perms',
    'access arguments' => array('administer google analytics counter'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 5,
    );

  /* OAuth callback from Google */
  $items['google_analytics_counter/oauth'] = array(
    'title' => 'Google Analytics Reports OAuth Callback',
    'access callback' => TRUE,
    'page callback' => 'google_analytics_counter_oauth_callback',
    'type' => MENU_CALLBACK,
    );

  return $items;
}

/**
 * Redirect to the module's permission settings. A callback from hook_menu().
 */
function google_analytics_counter_perms() {
  drupal_goto('admin/people/permissions', array('fragment' => 'module-google_analytics_counter'));
}

/**
 * Implements hook_block_info().
 */
function google_analytics_counter_block_info() {
  $block = array();

  // Generate listing of blocks from this module, for the admin/block page
  $block[0]["info"] = t("Google Analytics Counter");

  return $block;
}

/**
 * Implements hook_block_view().
 */
function google_analytics_counter_block_view($delta) {
  $block = array();

  // Generate our block content

  $block_content = google_analytics_counter_display();
  $block['subject'] = 'Google Analytics Counter';
  if ($block_content == '') { 
    // If unknown, for some reason.
    $block['content'] = 0; // Instead of t('N/A'). Suppose better to use 0 because it's true, that path has been recorded zero times by GA. Path may not exist or be private or too new.
  }
  else {
    $block['content'] = $block_content;
  }

  return $block;
}

/**
 * Implements hook_filter_info().
 */
function google_analytics_counter_filter_info() {
  $filters = array();
  $filters['filter_google_analytics_counter'] = array(
    'title' => t('Google Analytics Counter tag'),
    'description' => t('Substitutes a special Google Analytics Counter tag [gac|...] with the actual content.'),
    'prepare callback' => 'google_analytics_counter_filter_google_analytics_counter_prepare',
    'process callback' => 'google_analytics_counter_filter_google_analytics_counter_process',
      //'tips callback' => '_filter_example_filter_time_tips',
    );
  return $filters;
}

function google_analytics_counter_filter_google_analytics_counter_prepare($text, $filter) {
  return $text;
}

function google_analytics_counter_filter_google_analytics_counter_process($text, $filter) {
  $text = replace_google_analytics_counter_tags($text);
  return $text;
}

function replace_google_analytics_counter_tags($str) {
  // [gac|path/to/page]

  $matchlink = '';
  $orig_match = '';
  $matches = '';
  preg_match_all("/(\[)gac[^\]]*(\])/s", $str, $matches);

  foreach ($matches[0] as $match) {

    // Keep original value.
    $orig_match[] = $match;

    // Remove wrapping [].
    $match = substr($match, 1, (strlen($match) - 2));

    // Create an array of parameter attributions.
    $match = explode("|", $match);

    $path = trim(check_plain(@$match[1]));

    /* So now we can display the count based on the path.
     * If no path was defined, the function will detect the current page's count.
     */
    $matchlink[] = google_analytics_counter_display($path);
  }

  $str = str_replace($orig_match, $matchlink, $str);
  return $str;
}

/**
 * @todo Please document this function.
 */
function google_analytics_counter_display($path = '') {

  if ($path == '') {
    $path = check_plain($_GET['q']);
    //dpm($path);
  }

  $block_content = '';
  //$block_content .= '<span id="google-analytics-counter-' . md5($path) . '">';
  $block_content .= '<span class="google-analytics-counter">';
  $count = google_analytics_counter_get_sum_per_path($path);
  if ($count == '') { 
    // If unknown, for some reason.
    $block_content .= 0; // Better than t('N/A').
  }
  else {
    $block_content .= $count;
  }
  $block_content .= '</span>';

  return $block_content;
}

/**
 * @todo Please document this function.
 */
function google_analytics_counter_construct_content($sumarray) {

  $result = '';

  $sum_of_pageviews = '';

  $sum_of_pageviews .= @$sumarray[0];

  if (@$sumarray[0] == 0) {
    //@todo
    // If $sumarray[2] is zero, it means nothing was fetched (cache expired but there was concurrency and new data could not be retrieved). We will return nothing -- until new value can be retrieved.
    $result = '';
  }
  else {
    $result .= $sum_of_pageviews;
  }

  return $result;
}


/**
 * Implements hook_cron().
 *
 */
function google_analytics_counter_cron() {
  // Defaults to an hourly interval. Of course, cron has to be running at least hourly for this to work.
  $interval = 60*variable_get('google_analytics_counter_cron_interval', 60); // $interval must contain value in seconds.
  // We don't want to act every time cron runs (which could be every minute) so keep a time for the next run in a variable.
  if (REQUEST_TIME >= variable_get('google_analytics_counter_cron_next_execution', 0)) {
    google_analytics_counter_update_path_counts();
    variable_set('google_analytics_counter_cron_next_execution', REQUEST_TIME + $interval);
  }
  else {
    //watchdog('Google Analytics Counter', 'GA cron NOT running ... too little time passed!', NULL, WATCHDOG_ERROR);
  }
}

/**
 * Sets the expiry timestamp for cached queries.
 * Default is 3 days.
 * @return The UNIX timestamp to expire the query at.
 */
function google_analytics_counter_cache_time() {
  return time() + variable_get('google_analytics_counter_cache_length', 259200);
}

/**
 * More information relevant to Google Analytics statistics for this site.
 */
function google_analytics_counter_details(){
  $result = '';

  $result .= '<p><h3>More information relevant to Google Analytics statistics for this site:</h3>';

  $result .= '<p>Number of paths on this site as currently recorded by Google Analytics: ' . number_format(variable_get('google_analytics_counter_totalhits', 0)) . '. This is cumulative; paths that may no longer exist on the website still have historical traces in Google Analytics.';

  $dbresult = db_select('google_analytics_counter', 'gac')
  ->fields('gac')
  ->execute();
  $num_of_results = $dbresult->rowCount();
  $result .= '<p>Number of paths currently stored in local database table: ' . number_format($num_of_results) . '. This table is initially built and then regularly updated during cron runs.';

  $result .= '<br />The most recent retrieval of ' . number_format(variable_get('google_analytics_counter_chunk_to_fetch', 1000)) . ' paths from Google Analytics took ' . number_format(variable_get('google_analytics_counter_chunk_process_time', 'UNKNOWN')) . ' seconds.';

  $dbresult = db_select('node_counter', 'nc')
  ->fields('nc')
  ->execute();
  $num_of_results = $dbresult->rowCount();
  $result .= '<p>Number of nodes with known pageview counts on this site: ' . number_format($num_of_results) . '. Pageviews are updated the first time the node is accessed.';

  $apicalls = variable_get('google_analytics_counter_dayquota', array(0, 0));
  $remainingcalls = variable_get('google_analytics_counter_api_dayquota', 10000)-$apicalls[1];
  if ($remainingcalls < 1) $remainingcalls = '0';
  $result .= '<p>Number of requests made to Google Analytics: ' . number_format($apicalls[1]) . '. Only calls made by this module are counted here. Other modules and apps may be making more requests. ';
  $result .= 'Remaining requests available in the current 24-hour period: ' . number_format($remainingcalls) . '. ';
  $result .= 'The current 24-hour period ends in: ' . number_format(ceil((REQUEST_TIME-$apicalls[0])/60)) . ' minutes.';
  
  return $result;
}
