google_analytics_counter.settings:
  type: mapping
  label: Settings
  mapping:
    cron_interval:
      type: integer
    chunk_to_fetch:
      type: integer
    api_dayquota:
      type: integer
    cache_length:
      type: integer
    start_date:
      type: string
    overwrite_statistics:
      type: boolean
    profile_id:
      type: string
    client_id:
      type: string
    client_secret:
      type: string
    redirect_uri:
      type: string
